ignoredBuiltDependencies:
  - '@parcel/watcher'

onlyBuiltDependencies:
  - '@fortawesome/fontawesome-common-types'
  - '@fortawesome/fontawesome-svg-core'
  - '@fortawesome/free-regular-svg-icons'
  - '@fortawesome/free-solid-svg-icons'
  - electron
  - electron-winstaller
  - esbuild
  - sqlite3
